releaser.maven.build-command: ./scripts/integration-tests.sh
releaser.maven.deploy-command: ./mvnw deploy -DskipTests -B -Pfast,deploy {{systemProps}} && ./mvnw dockerfile:push -pl :spring-cloud-kubernetes-configuration-watcher -Pdockerpush
