spring:
  application:
    name: kubernetesconfigserver
  main:
    cloud-platform: kubernetes
  cloud:
    kubernetes:
      client:
        namespace: default

server:
  port: 8888

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: "optional:kubernetes:"
